### ISSUE TITLE
ProjectsFilter.jsx bug

### ISSUE THREAD

**Issue by TomZhong-au** [realstoman/nextjs-tailwindcss-portfolio#12]
this bug affects the projects' dropdown menu.

at line 30, the value is now set to a setState function and the console will print errors. it should be replaced with an empty string "".

![image](https://user-images.githubusercontent.com/95953466/236613000-3c6333e2-aead-4578-a85a-88b54e816a7c.png)

**Comment by realstoman** [comment]
This issue is fixed
