### ISSUE TITLE
theme issue

### ISSUE THREAD

**Issue by TomZhong-au** [realstoman/nextjs-tailwindcss-portfolio#13]
if the user 
1. most recently close the page with dark theme; 
2. when it re-open the page, there will be an hydration error;

I think the reason is that when next js generate the page at server, it is intended to be in 'light' mode, but when it gets to the client side, it then knows it should be in 'dark' mode.

I have not figured out how to fix this as I am not sure how this dark mode works. Would be happy to submit PR if realstoman or someone give me some idea.

**Comment by realstoman** [comment]
The issue is fixed
